type: web
name: weather-app
runtime: python
buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn app:app --bind :10000 --worker-class gthread --workers 1 --threads 4"
envVars:
  - key: PORT
    value: 10000
  - key: OPENWEATHER_API_KEY
    value: "<your_openweather_api_key_here>"
